name: graphql_codegen_example

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  json_annotation: ^4.0.1
  graphql: "^5.0.0"

dev_dependencies:
  json_serializable: ^5.0.0
  graphql_codegen_flutter:
    path: "../"
  build_runner: ^2.0.3
